name: CI Pipeline

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  backend:
    name: Backend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run Tests
        run: |
          cd backend
          pytest --maxfail=5 --disable-warnings --cov=app tests/

      - name: Lint Code
        run: |
          pip install flake8
          flake8 backend --max-line-length=88

  frontend:
    name: Frontend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          cd frontend
          npm install

      - name: Run Tests
        run: |
          npm test -- --watchAll=false

      - name: Lint Code
        run: |
          npm run lint
